-- DecodeLabs Project 3 - The Data Warehouse (AWS RDS MySQL)
-- Interns table with PRIMARY KEY, UNIQUE, NOT NULL

CREATE TABLE IF NOT EXISTS Interns (
  id INT AUTO_INCREMENT PRIMARY KEY,
  Name  VARCHAR(100) NOT NULL,
  Role  VARCHAR(100) NOT NULL,
  Email VARCHAR(150) NOT NULL UNIQUE
);
